In [379]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow_hub as hub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

In [380]:
df_train = pd.read_csv("TENSORFLOW_DATA.csv")
df_test = pd.read_csv("TENSORFLOW_TES.csv")

In [381]:
df = pd.concat([df_train,df_test])
df

(p) R  R (2)  R (5)  (p) G  G (2)  G (5)  (p) B  B (2)  B (5)  \
0     131    133    135    131    156    159     77     88     82   
1      66     23     15     22     16     11      1     16     13   
2     221    231    243    221    232    243    225    228    241   
3     209    214    225    209    118    134    224    151    168   
4     144    202    220    144    214    234    138    206    228   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5     225    205    213    101    207    214    142    211    217   
6     216     86     79    217    105     99    220    133    129   
7     175     96    117     30     59     71     29     31     35   
8     221    182    169     95    128     99    205     73     41   
9      84     86     76     51     53     45     25     27     22   

    (p) GreyScale  GreyScale (2)  GreyScale (5)  garut  solo  
0             125            141            143      1     0  
1               0             18             12      0     1  
2             212            231            243      1     0  
3             204            150            165      1     0  
4             140            210            229      1     0  
..            ...            ...            ...    ...   ...  
5             223            207            214      0     1  
6             216            103             96      1     0  
7              29             67             81      0     1  
8             186            138            113      1     0  
9              48             60             52      0     1  

[110 rows x 14 columns]

In [382]:
X = df[df.columns[:-2]].values
y1 = df[df.columns[-1]].values
y2 = df[df.columns[-2]].values
Y = pd.DataFrame({"garut":y2,
                    "solo":y1}).values

In [383]:
Y

array([[1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0,

In [384]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
# data = np.hstack((X, np.reshape(Y, (-1, 1))))
data = np.hstack((X, Y))
transformed_df = pd.DataFrame(data, columns=df.columns)

In [385]:
transformed_df

(p) R     R (2)     R (5)     (p) G     G (2)     G (5)     (p) B  \
0    0.137784  0.055752  0.206278  0.569406  0.814669  0.882016 -0.090073   
1   -0.704951 -1.554282 -1.342570 -0.975554 -1.310315 -1.163166 -1.078278   
2    1.304649  1.490147  1.600242  1.845062  1.968232  2.042795  1.834326   
3    1.149067  1.241324  1.367915  1.674974  0.237888  0.536546  1.821323   
4    0.306332  1.065683  1.303379  0.753668  1.695020  1.918425  0.703091   
..        ...       ...       ...       ...       ...       ...       ...   
105  1.356510  1.109593  1.213030  0.144188  1.588771  1.642050  0.755102   
106  1.239824 -0.632172 -0.516517  1.788366  0.040568  0.052888  1.769313   
107  0.708252 -0.485805 -0.026049 -0.862163 -0.657641 -0.334038 -0.714203   
108  1.304649  0.772950  0.645119  0.059144  0.389672  0.052888  1.574272   
109 -0.471578 -0.632172 -0.555239 -0.564510 -0.748712 -0.693327 -0.766214   

        B (2)     B (5)  (p) GreyScale  GreyScale (2)  GreyScale (5)  garut  \
0   -0.002329 -0.009424       0.258579       0.507899       0.596410    1.0   
1   -1.087287 -0.963161      -1.181464      -1.427294      -1.256203    0.0   
2    2.107313  2.188317       1.260849       1.923893       2.010619    1.0   
3    0.947010  1.179291       1.168686       0.649498       0.907536    1.0   
4    1.775798  2.008627       0.431384       1.593494       1.812630    1.0   
..        ...       ...            ...            ...            ...    ...   
105  1.851142  1.856582       1.387573       1.546294       1.600499    0.0   
106  0.675770  0.640222       1.306931      -0.089966      -0.068268    1.0   
107 -0.861254 -0.659071      -0.847374      -0.656363      -0.280399    0.0   
108 -0.228362 -0.576137       0.961320       0.460699       0.172148    1.0   
109 -0.921530 -0.838761      -0.628487      -0.766496      -0.690520    0.0   

     solo  
0     0.0  
1     1.0  
2     0.0  
3     0.0  
4     0.0  
..    ...  
105   1.0  
106   0.0  
107   1.0  
108   0.0  
109   1.0  

[110 rows x 14 columns]

In [386]:
len(transformed_df[transformed_df["garut"]==1]), len(transformed_df[transformed_df["solo"]==0])

(55, 55)

In [387]:
X[:100].shape
Y[:100].shape

(100, 2)

In [388]:
X_train, X_valid, Y_train, Y_valid = train_test_split(X[:100], Y[:100], test_size=0.8, random_state=0)

In [389]:
model = tf.keras.Sequential([
                             tf.keras.layers.Dense(12, activation='relu'), # if x <= 0 --> 0, x > 0 --> x
                             tf.keras.layers.Dense(24, activation='relu'), #bisa ganti
                             tf.keras.layers.Dense(2, activation="sigmoid") #bisa ditambah
])

In [390]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), #ganti
              loss=tf.keras.losses.BinaryCrossentropy(), #ganti
              metrics=['accuracy'])

In [391]:
model.evaluate(X_train, Y_train)

1/1 [==============================] - 0s 148ms/step - loss: 0.7514 - accuracy: 0.3500


[0.7514148354530334, 0.3499999940395355]

In [392]:
model.evaluate(X_valid, Y_valid)

3/3 [==============================] - 0s 2ms/step - loss: 0.8054 - accuracy: 0.2125


[0.805378794670105, 0.21250000596046448]

In [393]:
model.fit(X_train, Y_train, batch_size=16, epochs=100, validation_data=(X_valid, Y_valid))

Epoch 1/100
2/2 [==============================] - 1s 48ms/step - loss: 0.7493 - accuracy: 0.3500 - val_loss: 0.7878 - val_accuracy: 0.2375
Epoch 2/100
2/2 [==============================] - 0s 30ms/step - loss: 0.7347 - accuracy: 0.3500 - val_loss: 0.7712 - val_accuracy: 0.2625
Epoch 3/100
2/2 [==============================] - 0s 31ms/step - loss: 0.7208 - accuracy: 0.3500 - val_loss: 0.7556 - val_accuracy: 0.2875
Epoch 4/100
2/2 [==============================] - 0s 32ms/step - loss: 0.7084 - accuracy: 0.4000 - val_loss: 0.7409 - val_accuracy: 0.3500
Epoch 5/100
2/2 [==============================] - 0s 34ms/step - loss: 0.6971 - accuracy: 0.4500 - val_loss: 0.7270 - val_accuracy: 0.4250
Epoch 6/100
2/2 [==============================] - 0s 56ms/step - loss: 0.6861 - accuracy: 0.4500 - val_loss: 0.7140 - val_accuracy: 0.4875
Epoch 7/100
2/2 [==============================] - 0s 31ms/step - loss: 0.6754 - accuracy: 0.5000 - val_loss: 0.7017 - val_accuracy: 0.5750
Epoch 8/100
2/2 [===

In [394]:
X_test = X[100:]


In [395]:
model.save

<bound method Model.save of <keras.engine.sequential.Sequential object at 0x000002658BFB5D50>>

In [416]:
result = model.predict(X_test)

1/1 [==============================] - 0s 16ms/step


In [417]:
persenan =result
persenan

array([[0.622949  , 0.32708558],
       [0.8787025 , 0.11092199],
       [0.39861682, 0.5593198 ],
       [0.01048894, 0.9742571 ],
       [0.8928176 , 0.07951988],
       [0.9950997 , 0.00415443],
       [0.9955248 , 0.00439631],
       [0.04926543, 0.91931605],
       [0.9416572 , 0.04675157],
       [0.03706929, 0.93853146]], dtype=float32)

In [418]:
a = np.hsplit(result,2)

In [419]:
kiri = a[0]

In [420]:
kanan = a[1]

In [421]:
for i in range(10):
    for j in range(1):
        if kiri[i][j] < kanan[i][j]:
            print("[0,1] = Solo")
        else:
            print("[1,0] = Garut")

[1,0] = Garut
[1,0] = Garut
[0,1] = Solo
[0,1] = Solo
[1,0] = Garut
[1,0] = Garut
[1,0] = Garut
[0,1] = Solo
[1,0] = Garut
[0,1] = Solo


In [422]:
result = np.around(result)

In [423]:
result

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [424]:
print("        Garut     Solo")
persenan

        Garut     Solo


array([[0.622949  , 0.32708558],
       [0.8787025 , 0.11092199],
       [0.39861682, 0.5593198 ],
       [0.01048894, 0.9742571 ],
       [0.8928176 , 0.07951988],
       [0.9950997 , 0.00415443],
       [0.9955248 , 0.00439631],
       [0.04926543, 0.91931605],
       [0.9416572 , 0.04675157],
       [0.03706929, 0.93853146]], dtype=float32)

In [425]:
print("        Garut     Solo")
persenan

        Garut     Solo


array([[0.622949  , 0.32708558],
       [0.8787025 , 0.11092199],
       [0.39861682, 0.5593198 ],
       [0.01048894, 0.9742571 ],
       [0.8928176 , 0.07951988],
       [0.9950997 , 0.00415443],
       [0.9955248 , 0.00439631],
       [0.04926543, 0.91931605],
       [0.9416572 , 0.04675157],
       [0.03706929, 0.93853146]], dtype=float32)